{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.itrubnikov",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1383,
          "sha512": "68be41343974deb66adb748e5340a403f930c4f82785701d2ddb520cd4d2dda7ce06c104adaccebb8b10c07328ff549c6d35a3d88ba8878ab1689054a5a01877",
          "sha256": "16359f0e9024142037c5f464f6d638555343a70885a049829f67ce24894f6dd8",
          "sha1": "ec1caa97c5018bdaa26e622160750d8000848bb5",
          "md5": "0348c3af7c7d32dce99c5b391aa967b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1383,
          "sha512": "68be41343974deb66adb748e5340a403f930c4f82785701d2ddb520cd4d2dda7ce06c104adaccebb8b10c07328ff549c6d35a3d88ba8878ab1689054a5a01877",
          "sha256": "16359f0e9024142037c5f464f6d638555343a70885a049829f67ce24894f6dd8",
          "sha1": "ec1caa97c5018bdaa26e622160750d8000848bb5",
          "md5": "0348c3af7c7d32dce99c5b391aa967b1"
        }
      ]
    }
  ]
}
